apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-demo
  namespace: default
  labels:
    app: myapp-vol
    tier: fronted
spec:
  containers:
  - name: myapp-vol
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
      - name: https
      containerPort: 443
    volumeMounts:
    - name: html
      mountPath: /data/web/html/
  - name: busybox

    image: busybox
    # imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: html
      mountPath: /data/
  volumes:
  - name: html
    emptyDir: {}
      # medium:
      # sizeLimit:
