#   快速安装k8s的基础软件
#   1，请安装ansible
#   2，添加主机组
#   cat ／etc/ansible/hosts
#
#   [k8s]
#   192.168.1.x  node01
#   192.168.1.x  node02
#   192.168.1.x  node02
#   192.168.1.x  node04
#
#   3，运行ansible-playbook k8s_ansible.yaml即可完成初始环境的配置
#   4，在master节点kubeadm init node节点 kubeadm join
- hosts: jenkins
  remote_user: ubuntu
  gather_facts: false
  tasks:
  - name: test1
    # command: /mnt/jenkins/scripts/ucloud_ulb/setUlb_linux_amd64 ulb_id backend_id 0
    raw: /mnt/jenkins/scripts/ucloud_ulb/setUlb_linux_amd64 "{{ulb_id}}" "{{backend_id}}" 0
